- Dfe.Academies.Academisation.Core.Test/Dfe.Academies.Academisation.Core.Test.csproj
- Dfe.Academies.Academisation.Core.Test/DfeAssertions.cs
- Dfe.Academies.Academisation.IService/RequestModels/ContributorRequestModel.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationCreateTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationCreateTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/Dfe.Academies.Academisation.SubcutaneousTest.csproj
- Dfe.Academies.Academisation.SubcutaneousTest/Usings.cs
- Dfe.Academies.Academisation.sln
Added Subcutaneous tests project and two tests:
* happy path for Create Application
* unhappy path for Create Application
Jimmy Bogard has a useful, if somewhat old, article on Subcutaneous Testing:
https://lostechies.com/jimmybogard/2010/08/25/an-effective-testing-strategy/
> Subcutaneous tests

- Dfe.Academies.Academisation.IntegrationTest/ConversionAdvisoryBoardDecision/AdvisoryBoardDecisionCollection.cs
- Dfe.Academies.Academisation.IntegrationTest/ConversionAdvisoryBoardDecision/GetTests.cs
- Dfe.Academies.Academisation.IntegrationTest/ConversionAdvisoryBoardDecision/PostTests.cs
- Dfe.Academies.Academisation.IntegrationTest/Dfe.Academies.Academisation.IntegrationTest.csproj
- Dfe.Academies.Academisation.IntegrationTest/Extensions/HttpClientExtensions.cs
- Dfe.Academies.Academisation.IntegrationTest/TestWebApplicationFactory.cs
- Dfe.Academies.Academisation.WebApi/Dfe.Academies.Academisation.WebApi.csproj
- Dfe.Academies.Academisation.WebApi/Program.cs
Add integration tests for record a decision
Add TestWebApplicationFactory for IntegrationTests
Add functionality to use SQLite if no connection string is found in settings (for build pipeline tests)
Update Program to make accessible from integration tests
> Add integration test for record decision

- Dfe.Academies.Academisation.Core.Test/DfeAssertions.cs
- Dfe.Academies.Academisation.Data.UnitTest/Contexts/TestApplicationUnseededContext.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationUpdateTests.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/Application.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/UpdateApplicationValidator.cs
- Dfe.Academies.Academisation.IDomain/ApplicationAggregate/IApplication.cs
- Dfe.Academies.Academisation.Service.UnitTest/Commands/ApplicationUpdateCommandTests.cs
- Dfe.Academies.Academisation.Service/Commands/ApplicationUpdateCommand.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationUpdateTests.cs
- Dfe.Academies.Academisation.WebApi.UnitTest/Controller/ConversionApplicationControllerTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/ApplicationController.cs
Happy path subcutaneous test for Update Application
> Subcutaneous tests update application

- Dfe.Academies.Academisation.Core.Test/DfeAssert.cs
- Dfe.Academies.Academisation.Core.Test/DfeAssertions.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationUpdateTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationCreateTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationUpdateTests.cs
Minor tidy up to move some repeated logic and shorten the names.
> Refactor assertions

- Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacyApplicationServiceModelMapper.cs
- Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacyKeyPersonServiceModelMapper.cs
- Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacySchoolServiceModelMapper.cs
Initial mapping of what we have so far to the legacy service model. This gives us a good idea how much is left to build to have full field coverage.
> 104570 legacy application get

- Dfe.Academies.Academisation.Domain.Core/OutsideData/EstablishmentDetails.cs
- Dfe.Academies.Academisation.Domain.Core/OutsideData/MisEstablishmentDetails.cs
- Dfe.Academies.Academisation.Domain.Core/ProjectAggregate/ProjectDetails.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ProjectAggregate/ProjectCreateTests.cs
- Dfe.Academies.Academisation.Domain/ProjectAggregate/Project.cs
- Dfe.Academies.Academisation.Domain/ProjectAggregate/ProjectFactory.cs
- Dfe.Academies.Academisation.IDomain/ProjectAggregate/IProjectFactory.cs
- Dfe.Academies.Academisation.Service.UnitTest/Commands/ApplicationSubmitCommandTests.cs
- Dfe.Academies.Academisation.Service/Commands/Application/ApplicationSubmitCommand.cs
Beginning to map the project from the application.
> AB#104571 Submit Application Create Project - Map Establishment & MisEstablishment to ProjectDetails in domain

- Dfe.Academies.Academisation.Domain/ProjectAggregate/Project.cs
- Dfe.Academies.Academisation.Service/Commands/Application/ApplicationSubmitCommand.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationSubmitTests.cs
@MarkRobinsonDfe I'm not quite able to map some of the fields associated with the project. Would you mind adding these soon so that I can complete the project work.
> AB#104571 Submit Application Create Project - mapping more fields in the project domain

- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationSubmitTests.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/SubmitApplicationValidator.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/SubmitJoinAMatApplicationValidator.cs
Adding validation for number of schools on Submit Application
> 104571 Submit Application Create Project - validate number of schools

- Dfe.Academies.Academisation.IService/Dfe.Academies.Academisation.IService.csproj
- Dfe.Academies.Academisation.IService/ServiceModels/Legacy/ProjectAggregate/LegacyProjectServiceModel.cs
- Dfe.Academies.Academisation.Service/Mappers/Legacy/ProjectAggregate/LegacyProjectDetailsMapper.cs
- Dfe.Academies.Academisation.Service/Mappers/Legacy/ProjectAggregate/LegacyProjectServiceModelMapper.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ProjectAggregate/LegacyProjectUpdateTests.cs
Addresses bug where data in the project table was being overwritten with empty values.
> AB#106546 update project - fix issue where data was being overwritten with null values.

- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationUpdateTests.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/SchoolValidator.cs
Added a validator to the school details on an update to check that the URN is valid, in this case greater than zero.
> AB#105402- School urn greater than zero

- Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationSchoolState.cs
- Dfe.Academies.Academisation.Data/Migrations/20221005103010_SchoolFinancialInvestigations.Designer.cs
- Dfe.Academies.Academisation.Data/Migrations/20221005103010_SchoolFinancialInvestigations.cs
- Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/SchoolDetails.cs
- Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationSchoolServiceModel.cs
- Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationSchoolServiceModelMapper.cs
- Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacySchoolServiceModelMapper.cs
Ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/106658?McasTsid=26110
Exposing 3 new JSON properties:-
"financeOngoingInvestigations": true,
"financialInvestigationsExplain": "string",
"financialInvestigationsTrustAware": true
n/a
1. Go to put endpoint confirm new JSON properties
2. go to get endpoint confirm new JSON properties
3. Confirm new columns created in database
n/a
> AB#106658 - API - School Financial Investigations - additional properties

- Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationSchoolState.cs
- Dfe.Academies.Academisation.Data/Migrations/20221005130941_SchoolDeclaration.Designer.cs
- Dfe.Academies.Academisation.Data/Migrations/20221005130941_SchoolDeclaration.cs
- Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/SchoolDetails.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/School.cs
- Dfe.Academies.Academisation.IDomain/ApplicationAggregate/ISchool.cs
- Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationSchoolServiceModel.cs
- Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationSchoolServiceModelMapper.cs
- Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacySchoolServiceModelMapper.cs
Ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105473?McasTsid=26110
Exposing 3 new JSON properties:-
"declarationBodyAgree": true,
"declarationIAmTheChairOrHeadteacher": true,
"declarationSignedByName": "string"
n/a
1. Go to put endpoint confirm new JSON properties
2. go to get endpoint confirm new JSON properties
3. Confirm new columns created in database
n/a
> AB#105473 - API - Declaration -  additional properties

- Dfe.Academies.Academisation.Data.UnitTest/ProjectAggregate/ProjectListGetDataQueryTests.cs
- Dfe.Academies.Academisation.Data/ProjectAggregate/ProjectListGetDataQuery.cs
- Dfe.Academies.Academisation.IData/ProjectAggregate/IProjectListGetDataQuery.cs
- Dfe.Academies.Academisation.Service.UnitTest/Factories/PagingResponseFactoryTests.cs
- Dfe.Academies.Academisation.Service.UnitTest/Queries/LegacyProjectListGetQueryTests.cs
- Dfe.Academies.Academisation.Service/Factories/PagingResponseFactory.cs
- Dfe.Academies.Academisation.Service/Queries/LegacyProjectListGetQuery.cs
Returning count of total projects for search criteria rather than number of projects in the returned result.
> AB#101007 project filter - return total count of projects

- Dfe.Academies.Academisation.Core/Utils/DateTimeProvider.cs
- Dfe.Academies.Academisation.Core/Utils/IDateTimeProvider.cs
- Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationState.cs
- Dfe.Academies.Academisation.Data/Migrations/20221019095812_ApplicationSubmittedDate.Designer.cs
- Dfe.Academies.Academisation.Data/Migrations/20221019095812_ApplicationSubmittedDate.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationLeaseTests.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationLoanTests.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationSubmitTests.cs
- Dfe.Academies.Academisation.Domain.UnitTest/Services/ApplicationSubmissionServiceTests.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/Application.cs
- Dfe.Academies.Academisation.Domain/ApplicationSubmissionService.cs
- Dfe.Academies.Academisation.IDomain/ApplicationAggregate/IApplication.cs
- Dfe.Academies.Academisation.IService/Commands/Application/IApplicationSubmitCommand.cs
- Dfe.Academies.Academisation.IService/Commands/Application/SetFormTrustDetailsCommand.cs
- Dfe.Academies.Academisation.IService/Commands/Application/SetJoinTrustDetailsCommand.cs
- Dfe.Academies.Academisation.IService/Commands/Application/SubmitApplicationCommand.cs
- Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationServiceModel.cs
- Dfe.Academies.Academisation.Service.UnitTest/Commands/ApplicationSubmitCommandTests.cs
- Dfe.Academies.Academisation.Service/Commands/Application/ApplicationSubmitCommandHandler.cs
- Dfe.Academies.Academisation.Service/Commands/Application/FormTrustCommandHandler.cs
- Dfe.Academies.Academisation.Service/Commands/Application/JoinTrustCommandHandler.cs
- Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationServiceModelMapper.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationCreateTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationSubmitTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationUpdateTests.cs
- Dfe.Academies.Academisation.WebApi.UnitTest/Controller/ConversionApplicationControllerTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/ApplicationController.cs
- Dfe.Academies.Academisation.WebApi/Program.cs
Application submitted date added to application
> 106651 submit application

- Dfe.Academies.Academisation.Data.UnitTest/ProjectAggregate/ProjectStatusesDataQueryTests.cs
- Dfe.Academies.Academisation.Data/ProjectAggregate/ProjectStatusesDataQuery.cs
- Dfe.Academies.Academisation.IData/ProjectAggregate/IProjectGetStatusesDataQuery.cs
- Dfe.Academies.Academisation.IService/Query/IProjectGetStatusesQuery.cs
- Dfe.Academies.Academisation.Service/Queries/ProjectGetStatusesQuery.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationSubmitTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ProjectAggregate/LegacyProjectGetStatusesTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ProjectAggregate/LegacyProjectGetTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ProjectAggregate/LegacyProjectListGetTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ProjectAggregate/LegacyProjectUpdateTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/LegacyProjectController.cs
- Dfe.Academies.Academisation.WebApi/Program.cs
> AB#109483 filter project - add new endpoint for getting all available statuses

- Dfe.Academies.Academisation.Data/ApplicationAggregate/JoinTrustState.cs
- Dfe.Academies.Academisation.Data/Migrations/20221111154804_TrustChangesBoolToInt.Designer.cs
- Dfe.Academies.Academisation.Data/Migrations/20221111154804_TrustChangesBoolToInt.cs
- Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/ChangesToTrust.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationUpdateTests.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/Application.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/Trusts/JoinTrust.cs
- Dfe.Academies.Academisation.IDomain/ApplicationAggregate/IApplication.cs
- Dfe.Academies.Academisation.IDomain/ApplicationAggregate/IJoinTrust.cs
- Dfe.Academies.Academisation.IService/Commands/Application/SetJoinTrustDetailsCommand.cs
- Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationJoinTrustServiceModel.cs
- Dfe.Academies.Academisation.WebApi.UnitTest/AutoMapper/AutoMapperSetupTests.cs
Changes to a trust property changed from a bool to an enum yes/no/unknown.
> AB#104661 - changes to a trust

- Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationSchoolState.cs
- Dfe.Academies.Academisation.Data/Migrations/20221116164050_HasLoansHasLeases.Designer.cs
- Dfe.Academies.Academisation.Data/Migrations/20221116164050_HasLoansHasLeases.cs
- Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/UpdateSchoolParameter.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationLeaseTests.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationLoanTests.cs
- Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationUpdateTests.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/Application.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/Schools/School.cs
- Dfe.Academies.Academisation.IDomain/ApplicationAggregate/ISchool.cs
- Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationSchoolServiceModel.cs
- Dfe.Academies.Academisation.Service/Commands/Application/ApplicationUpdateCommand.cs
- Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationSchoolServiceModelMapper.cs
added hasLoans and hasLeases to the school on the application
> AB108901-hasLoans and hasLeases bool field on school

- Dfe.Academies.Academisation.Data.UnitTest/ApplicationAggregate/ApplicationUpdateDataCommandTests.cs
- Dfe.Academies.Academisation.Data.UnitTest/ConversionAdvisoryBoardDecisionAggregate/ConversionAdvisoryBoardDecisionUpdateTests.cs
- Dfe.Academies.Academisation.Data/AcademisationContext.cs
- Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationUpdateDataCommand.cs
- Dfe.Academies.Academisation.WebApi/Controllers/ApplicationController.cs
Form mat set details was broken by some key people changes fixed and dev tested both areas of functionality are still working
> bug fix for form mat details exception in api

- terraform/README.md
- terraform/container-apps-hosting.tf
* Contains a fix which disables the CDN cache
> Bump terraform container app hosting module to v0.10.1

- .github/workflows/build-and-push-image-development.yml
- .github/workflows/build-and-push-image-production.yml
* Builds and pushes a given release tag to Azure ACR Production environment
> Add Production build and push workflow

- .github/workflows/build-and-push-image-test.yml
* Updates the container app after the new release has been pushed to ACR
> Add container app update to the Test workflow

- .github/workflows/build-and-push-image-development.yml
- .github/workflows/build-and-push-image-production.yml
- .github/workflows/build-and-push-image-test.yml
- .github/workflows/continuous-integration-image-build-test.yml
- .github/workflows/continuous-integration-terraform.yml
- .github/workflows/continuous-integration-tfsec.yml
Updated workflow names. Open to suggestions if you think they could be made better.
> updating workflow names so they are distinguishable

- .github/workflows/build-and-push-image-production.yml
- Automates the restart of the Production container with the Prod image
> Added Production Container App restart automation

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
- Add NSG flow logs
- Add webhook receiver for Slack
> Add new options for Terraform module

- terraform/README.md
- terraform/container-apps-hosting.tf
Updates terraform hosting module from v0.14.2 to v0.14.3 which contains a bug fix to the blob storage app env var
> Updated Terraform module to v0.14.3

- Dfe.Academies.Academisation.Seed/ProjectConsts.cs
Changed seeding - 
changed the text for APPROVED WITH CONDITIONS to Approved with Conditions.
> Changed Approved with Conditions to title case

- Dfe.Academies.Academisation.Service/Mappers/Legacy/ProjectAggregate/LegacyProjectDetailsMapper.cs
Enable advisory board date to be cleared, set back to null
> 122025-bugfix-advisory-board-dates

- Dfe.Academies.Academisation.Data.UnitTest/Contexts/TestApplicationContext.cs
- Dfe.Academies.Academisation.Data/AcademisationContext.cs
- Dfe.Academies.Academisation.Data/Migrations/20230720115001_Deleted_at_added.Designer.cs
- Dfe.Academies.Academisation.Data/Migrations/20230720115001_Deleted_at_added.cs
- Dfe.Academies.Academisation.Data/Repositories/ApplicationRepository.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/Application.cs
- Dfe.Academies.Academisation.Domain/ApplicationAggregate/IApplicationRepository.cs
- Dfe.Academies.Academisation.Domain/Validations/DeleteApplicationValidator.cs
- Dfe.Academies.Academisation.IDomain/ApplicationAggregate/IApplication.cs
- Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationServiceModel.cs
- Dfe.Academies.Academisation.Service.UnitTest/Commands/ApplicationDeleteCommandTests.cs
- Dfe.Academies.Academisation.Service/Commands/Application/ApplicationDeleteCommand.cs
- Dfe.Academies.Academisation.Service/Commands/Application/ApplicationDeleteCommandHandler.cs
- Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationServiceModelMapper.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationCreateTests.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationDeleteTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/ApplicationController.cs
DeletedAt column added
controllers and commands added
unit tests updated
> migration and new field added delete functionality added

- Dfe.Academies.Academisation.IService/ServiceModels/TransferProject/AcademyTransferProjectSummaryResponse.cs
- Dfe.Academies.Academisation.IService/ServiceModels/TransferProject/TransferringAcademiesResponse.cs
- Dfe.Academies.Academisation.Service.UnitTest/Queries/TransferProjectQueryServiceTests.cs
- Dfe.Academies.Academisation.Service/Queries/TransferProjectQueryService.cs
Transfers domain - Get Transfer Projects Endpoint
> Transfers domain - Get Transfer Projects Endpoint

- DataConversion/Transfers/1-transfer-project.sql
- DataConversion/Transfers/2-transferring-academies.sql
- DataConversion/Transfers/3-intended-benefits.sql
- Dfe.Academies.Academisation.Service/Queries/TransferProjectQueryService.cs
Fix for record count when getting all transfers
> Transfers domain

- Dfe.Academies.Academisation.Data.UnitTest/ProjectAggregate/IncompleteProjectsGetDataQueryTests.cs
- Dfe.Academies.Academisation.Data.UnitTest/ProjectAggregate/ProjectGetDataQueryTests.cs
- Dfe.Academies.Academisation.Data/AcademisationContext.cs
- Dfe.Academies.Academisation.Data/ProjectAggregate/IncompleteProjectsGetDataQuery.cs
- Dfe.Academies.Academisation.Data/ProjectAggregate/ProjectCreateDataCommand.cs
- Dfe.Academies.Academisation.Data/ProjectAggregate/ProjectGetDataQuery.cs
- Dfe.Academies.Academisation.Data/ProjectAggregate/ProjectListGetDataQuery.cs
- Dfe.Academies.Academisation.Data/ProjectAggregate/ProjectState.cs
- Dfe.Academies.Academisation.Data/ProjectAggregate/ProjectUpdateDataCommand.cs
- Dfe.Academies.Academisation.Domain.Core/ProjectAggregate/ProjectDetails.cs
- Dfe.Academies.Academisation.Service/Commands/CypressData/CyAddSponsoredProjectCommandHandler.cs
- Dfe.Academies.Academisation.Service/Commands/CypressData/CyAddVoluntaryProjectCommandHandler.cs
> refactor of project state

- Dfe.Academies.Academisation.Domain/ProjectAggregate/Project.cs
- Dfe.Academies.Academisation.Service/Mappers/Legacy/ProjectAggregate/LegacyProjectDetailsMapper.cs
add mapping so PRU groups stop getting overwritten
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/150295
> add mapping so PRU groups stop getting overwritten

- Dfe.Academies.Academisation.Service/Queries/ConversionProjectExportService.cs
I have added the "Is part of PFI scheme" field to the end of the conversions export.
Ticket: https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/157615
> add pfi scheme to field

- .github/workflows/build-and-push-image.yml
- .github/workflows/security-tests.yml
Bumps actions versions to remove node 16 deprecation warnings
> Bump azure and docker actions versions

- Dfe.Academies.Academisation.IService/ServiceModels/TransferProject/AcademyTransferProjectResponse.cs
- Dfe.Academies.Academisation.Service/Mappers/TransferProject/AcademyTransferProjectResponseFactory.cs
to be used for advisory board decisions in the client app
> Bugfix to return transfer project Id in the api response 

- Dfe.Academies.Academisation.Service/Queries/ConversionProjectExportService.cs
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/164218
> Updated date formats to be sortable

- Dfe.Academies.Academisation.Service/Queries/AcademiesQueryService.cs
small change to use v4 endpoint for bulk establishment request
> v4 endpoint fix

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/versions.tf
Terraform CI tests were failing because this prose was not indented correctly
> Corrected syntax for versions.tf

- Dfe.Academies.Academisation.Domain.Core/ConversionAdvisoryBoardDecisionAggregate/DecisionMadeBy.cs
bugfix - enum - DeputyDirector and Grade6 wrong way round
> bugfix - enum DeputyDirector and Grade6 wrong way round

- Dfe.Academies.Academisation.Data/Repositories/ProjectGroupRepository.cs
- Dfe.Academies.Academisation.Domain/ProjectGroupsAggregate/IProjectGroupRepository.cs
- Dfe.Academies.Academisation.Domain/ProjectGroupsAggregate/ProjectGroup.cs
- Dfe.Academies.Academisation.Service.UnitTest/Commands/ProjectGroup/CreateProjectGroupCommandHandlerTests.cs
- Dfe.Academies.Academisation.Service/CommandValidations/ProjectGroup/CreateProjectGroupCommandValidator.cs
- Dfe.Academies.Academisation.Service/Commands/ProjectGroup/CreateProjectGroupCommand.cs
- Dfe.Academies.Academisation.Service/Commands/ProjectGroup/CreateProjectGroupCommandHandler.cs
- Dfe.Academies.Academisation.WebApi.UnitTest/Controller/ProjectGroupControllerTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/ProjectGroupController.cs
- Dfe.Academies.Academisation.WebApi/Program.cs
Added new Create project group endpoint with tests.
> Added new Create Project Group Endpoint

- Dfe.Academies.Academisation.Service.UnitTest/Commands/ProjectGroup/DeleteProjectGroupCommandHandlerTests.cs
- Dfe.Academies.Academisation.Service/Commands/ProjectGroup/DeleteProjectGroupCommand.cs
- Dfe.Academies.Academisation.Service/Commands/ProjectGroup/DeleteProjectGroupCommandHandler.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ProjectGroup/ProjectGroupTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/ProjectGroupController.cs
Added Delete project group endpoint
Added integration and unit tests.
> Feature/176671 - Added Delete project group endpoint

- Dfe.Academies.Academisation.Domain.Core/RoleCapabilitiesAggregate/RoleInfo.cs
- Dfe.Academies.Academisation.SubcutaneousTest/RoleCapabilities/RoleCapabilitiesTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/RoleCapabilitiesController.cs
Fixed error if no role is defined
> Fixed error if no role is defined

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/key-vault-tfvars-secrets.tf
- terraform/versions.tf
* https://github.com/DFE-Digital/terraform-azurerm-container-apps-hosting/releases/tag/v1.12.0
* https://github.com/DFE-Digital/terraform-azurerm-key-vault-tfvars
> Bump Terraform modules (v1.12, v0.5.0)

- Dfe.Academies.Academisation.Domain.Core/ConversionAdvisoryBoardDecisionAggregate/AdvisoryBoardDAORevokedReason.cs
> New DAO revoked reason for 'policy change'

- .github/workflows/build-and-push-image.yml
* Uses OIDC with Azure/login instead of Credential based authentication
* https://github.com/DFE-Digital/deploy-azure-container-apps-action/compare/v2.6.0...v3.0.0
>  Bump deploy-azure-container-apps-action v3.0.0

- Dfe.Academies.Academisation.Data/Migrations/20241030141951_imcoming-trust-reference-number-to-transfer-project.Designer.cs
- Dfe.Academies.Academisation.Data/Migrations/20241030141951_imcoming-trust-reference-number-to-transfer-project.cs
- Dfe.Academies.Academisation.Data/Repositories/ConversionProjectRepository.cs
- Dfe.Academies.Academisation.Data/Repositories/TransferProjectRepository.cs
- Dfe.Academies.Academisation.Domain.Core/RoleCapabilitiesAggregate/RoleCapability.cs
- Dfe.Academies.Academisation.Domain.Core/RoleCapabilitiesAggregate/RoleInfo.cs
- Dfe.Academies.Academisation.Domain/TransferProjectAggregate/TransferProject.cs
- Dfe.Academies.Academisation.Domain/TransferProjectAggregate/TransferringAcademy.cs
- Dfe.Academies.Academisation.IDomain/TransferProjectAggregate/ITransferProject.cs
- Dfe.Academies.Academisation.IDomain/TransferProjectAggregate/ITransferringAcademy.cs
- Dfe.Academies.Academisation.IService/ServiceModels/TransferProject/AcademyTransferProjectResponse.cs
- Dfe.Academies.Academisation.Service/Commands/Legacy/Project/EnrichProjectCommand.cs
- Dfe.Academies.Academisation.Service/Commands/TransferProject/SetTransferProjectTrustCommandHandler.cs
- Dfe.Academies.Academisation.Service/Mappers/CompleteProjects/CompleteTransferProjectServiceModelMapper.cs
- Dfe.Academies.Academisation.Service/Mappers/TransferProject/AcademyTransferProjectResponseFactory.cs
- Dfe.Academies.Academisation.SubcutaneousTest/RoleCapabilities/RoleCapabilitiesTests.cs
- Dfe.Academies.Academisation.WebApi/Services/CreateCompleteProjectsService.cs
manual trust reference number added to form a mat transfers
> add manual trust reference number to form a mat transfer

- Dfe.Academies.Academisation.Service/Commands/FormAMatProject/CreateFormAMatProjectsCommandHandler.cs
- auto generate TRN for form a mat A2B applications
> auto generate TRN for form a mat A2B applications

- Dfe.Academies.Academisation.Service/Commands/FormAMatProject/CreateFormAMatProjectsCommandHandler.cs
- Missing await causing transaction issues
> generate TRN await fix

- CypressTests/package-lock.json
- CypressTests/package.json
Minor Adjustment to package and package-lock.json conflicts with diff versions of lint
> Minor Adjustment to conflicts with diff versions of lint

- Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationServiceModel.cs
- Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationServiceModelMapper.cs
- Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationCreateTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/ApplicationController.cs
Returning A2B application `CreatedOn` Information for determining A2B application either a new application or existing application after passing the deadline.
Ticket : https://dev.azure.com/dfe-gov-uk/Academies-and-Free-Schools-SIP/_workitems/edit/191269
> Returning A2B application `CreatedOn` Information

- .github/workflows/cypress-tests.yml
- .gitignore
- CypressTests/cypress.config.js
- CypressTests/package-lock.json
- CypressTests/package.json
Added mocha mochawesome mochawesome-report-generator, updated package.json with report scripts, cypress-multi-reporters, cypress-slack-reporter, updated cypress-tests workflow
> Test get academisation api slack reporter ready

- .github/workflows/build-and-push-image.yml
* This will fix the invalid deployment workflow restoring service
> Add missing secret to workflow call

- Dfe.Academies.Academisation.IService/Query/IAcademiesQueryService.cs
- Dfe.Academies.Academisation.Service.UnitTest/Queries/AcademiesQueryServiceTests.cs
- Dfe.Academies.Academisation.Service.UnitTest/Queries/TransferProjectQueryServiceTests.cs
- Dfe.Academies.Academisation.Service/Queries/AcademiesQueryService.cs
- Dfe.Academies.Academisation.Service/Queries/ConversionProjectQueryService.cs
- Dfe.Academies.Academisation.Service/Queries/Models/UkprnRequestModel.cs
- Dfe.Academies.Academisation.Service/Queries/Models/UrnRequestModel.cs
- Dfe.Academies.Academisation.Service/Queries/TransferProjectQueryService.cs
- Dfe.Academies.Academisation.SubcutaneousTest/Export/ExportTests.cs
Ticket: https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/215979
> Excel exports fail if too many UKPRNs are queried

- Dfe.Academies.Academisation.Data/Repositories/ConversionProjectRepository.cs
- Dfe.Academies.Academisation.Data/Repositories/FormAMatProjectRepository.cs
- Dfe.Academies.Academisation.Data/Repositories/TransferProjectRepository.cs
- Dfe.Academies.Academisation.Domain/FormAMatProjectAggregate/IFormAMatProjectRepository.cs
- Dfe.Academies.Academisation.Domain/ProjectAggregate/IConversionProjectRepository.cs
- Dfe.Academies.Academisation.Domain/TransferProjectAggregate/ITransferProjectRepository.cs
- Dfe.Academies.Academisation.IDomain/TransferProjectAggregate/ITransferProject.cs
- Dfe.Academies.Academisation.IService/Query/ISummaryQueryService.cs
- Dfe.Academies.Academisation.IService/ServiceModels/Summary/ProjectSummary.cs
- Dfe.Academies.Academisation.Service/Queries/SummaryQueryService.cs
- Dfe.Academies.Academisation.SubcutaneousTest/Summary/SummaryQueryServiceTests.cs
- Dfe.Academies.Academisation.WebApi/Controllers/SummaryController.cs
Added form a mat to summary endpoint. This also refactors to use repository pattern.
> Add form a mat to summary endpoint
