DFE-Digital/academies-academisation-api

Dfe.Academies.Academisation.Data/Dfe.Academies.Academisation.Data.csproj
Dfe.Academies.Academisation.Data/ProjectAggregate/ProjectGetDataQuery.cs
Dfe.Academies.Academisation.Domain.Core/ProjectAggregate/ProjectDetails.cs
Dfe.Academies.Academisation.Domain/ProjectAggregate/Project.cs
Dfe.Academies.Academisation.IData/ProjectAggregate/IProjectGetDataQuery.cs
Dfe.Academies.Academisation.IDomain/Dfe.Academies.Academisation.IDomain.csproj
Dfe.Academies.Academisation.IDomain/ProjectAggregate/IProject.cs
Dfe.Academies.Academisation.IService/Dfe.Academies.Academisation.IService.csproj
Dfe.Academies.Academisation.IService/Query/ILegacyProjectGetQuery.cs
Dfe.Academies.Academisation.IService/ServiceModels/Legacy/ProjectAggregate/LegacyProjectServiceModel.cs
Dfe.Academies.Academisation.Service/Mappers/Legacy/ProjectAggregate/LegacyProjectServiceModelMapper.cs
Dfe.Academies.Academisation.Service/Queries/LegacyProjectGetQuery.cs
Dfe.Academies.Academisation.SubcutaneousTest/ApplicationAggregate/ApplicationCreateTests.cs
Dfe.Academies.Academisation.SubcutaneousTest/ProjectAggregate/ProjectGetTests.cs
Dfe.Academies.Academisation.WebApi.UnitTest/Controller/ConversionAdvisoryBoardDecisionControllerPostTests.cs
Dfe.Academies.Academisation.WebApi.UnitTest/Controller/ConversionApplicationControllerTests.cs
Dfe.Academies.Academisation.WebApi/Controllers/ApplicationController.cs
Dfe.Academies.Academisation.WebApi/Controllers/ConversionAdvisoryBoardDecisionController.cs
Dfe.Academies.Academisation.WebApi/Controllers/LegacyProjectController.cs
Dfe.Academies.Academisation.WebApi/Program.cs

Initial full stack code for Get Project. Have called it "Legacy" for now as I've copied and pasted the models from the Academies API, this gives us the flexibility to rename things in a future non-legacy version without breaking Manage a Conversion.
Data layer is faked for now, I thought I'd do that last so we don't have to churn the ef migrations if we rename things.
Also includes a bug fix for CreateProject which was using the wrong parameter names for CreateAtRoute (thank you @MartinWheelerMT for finding and fixing the bug!)

104572 get project

---

Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationSchoolState.cs
Dfe.Academies.Academisation.Data/Migrations/20220908092640_ApplicationPreSupportGrant.Designer.cs
Dfe.Academies.Academisation.Data/Migrations/20220908092640_ApplicationPreSupportGrant.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/PreOpeningSupportGrantType.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/SchoolDetails.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationSchoolServiceModel.cs
Dfe.Academies.Academisation.IService/ServiceModels/Legacy/ApplicationAggregate/LegacySchoolServiceModel.cs
Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationSchoolServiceModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacySchoolServiceModelMapper.cs

Adding pre-support grant onto GET & PUT endpoints as per this ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105464?McasTsid=26110
'SchoolSupportGrantFundsPaidTo' property to be present in GET && PUT endpoint
'ConfirmPaySupportGrantToSchool' property to be present in GET && PUT endpoint
And, within 'ApplicationSchool' table in sip DB
n/a
1. Run unit tests to ensure nothing broken
2. Run dotnet ef database update - to ensure new column created
3. run API to ensure new property is available on GET && PUT endpoints
n/a

105464 mk2

---

Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationSchoolState.cs
Dfe.Academies.Academisation.Data/Migrations/20220912094139_SchoolAdditionalInformation.Designer.cs
Dfe.Academies.Academisation.Data/Migrations/20220912094139_SchoolAdditionalInformation.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/EqualityImpactType.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/LocalAuthority.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/PartnershipsAndAffliations.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/Performance.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/ReligiousEducation.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/SchoolDetails.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationSchoolServiceModel.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/LocalAuthorityServiceModel.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/PartnershipsAndAffliationsServiceModel.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/PerformanceServiceModel.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/ReligiousEducationServiceModel.cs
Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationSchoolServiceModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Application/LocalAuthorityModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Application/PartnershipsAndAffliationsModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Application/PerformanceModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Application/ReligiousEducationModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacySchoolServiceModelMapper.cs

Adding additional information data capture onto GET & PUT endpoints as per this ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105888?McasTsid=26110
All additional information properties to be present in GET && PUT endpoint
All additional information properties to be present in Legacy GET endpoint
All additional information properties table in sip DB
n/a
1. Run unit tests to ensure nothing broken
2. Run dotnet ef database update - to ensure new column created
3. run API to ensure new properties are available on GET && PUT endpoints
4. run API to ensure new properties are available on legacy GET endpoint
n/a

105888 add additional info data storage

---

Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationSchoolState.cs
Dfe.Academies.Academisation.Data/Migrations/20220912152802_SchoolNextFinancialYear.Designer.cs
Dfe.Academies.Academisation.Data/Migrations/20220912152802_SchoolNextFinancialYear.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/SchoolDetails.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationSchoolServiceModel.cs
Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationSchoolServiceModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacySchoolServiceModelMapper.cs

Adding next financial year data capture onto GET & PUT endpoints as per this ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105470?McasTsid=26110
All additional next financial year properties to be present in GET && PUT endpoint
All additional next financial year properties to be present in Legacy GET endpoint
All additional next financial year properties table in sip DB
n/a
1. Run unit tests to ensure nothing broken
2. Run dotnet ef database update - to ensure new column created
3. run API to ensure new properties are available on GET && PUT endpoints
4. run API to ensure new properties are available on legacy GET endpoint
n/a

105470 school finances next financial year

---

Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationSchoolState.cs
Dfe.Academies.Academisation.Data/Migrations/20220913111614_SchoolPreviousFinancialYear.Designer.cs
Dfe.Academies.Academisation.Data/Migrations/20220913111614_SchoolPreviousFinancialYear.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/SchoolDetails.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationSchoolServiceModel.cs
Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationSchoolServiceModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacySchoolServiceModelMapper.cs

Adding previous financial year data capture onto GET & PUT endpoints as per this ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/105472?McasTsid=26110
All additional previous financial year properties to be present in GET && PUT endpoint
All additional previous financial year properties to be present in Legacy GET endpoint
All additional previous financial year properties table in sip DB
n/a
1. Run unit tests to ensure nothing broken
2. Run dotnet ef database update - to ensure new column created
3. run API to ensure new properties are available on GET && PUT endpoints
4. run API to ensure new properties are available on legacy GET endpoint
n/a

AB#105472 - API - School Finances - Previous financial year 

---

Dfe.Academies.Academisation.Data/ApplicationAggregate/ApplicationSchoolState.cs
Dfe.Academies.Academisation.Data/Migrations/20221005092601_SchoolConsultation.Designer.cs
Dfe.Academies.Academisation.Data/Migrations/20221005092601_SchoolConsultation.cs
Dfe.Academies.Academisation.Domain.Core/ApplicationAggregate/SchoolDetails.cs
Dfe.Academies.Academisation.Domain/ApplicationAggregate/School.cs
Dfe.Academies.Academisation.IService/ServiceModels/Application/ApplicationSchoolServiceModel.cs
Dfe.Academies.Academisation.IService/ServiceModels/Legacy/ApplicationAggregate/LegacySchoolServiceModel.cs
Dfe.Academies.Academisation.Service/Mappers/Application/ApplicationSchoolServiceModelMapper.cs
Dfe.Academies.Academisation.Service/Mappers/Legacy/ApplicationAggregate/LegacySchoolServiceModelMapper.cs

Ticket:-
https://dfe-gov-uk.visualstudio.com.mcas.ms/Academies-and-Free-Schools-SIP/_workitems/edit/108119?McasTsid=26110
- [] Bug fix (non-breaking change which fixes an issue)
Exposing 2 new JSON properties:-
"schoolHasConsultedStakeholders": true,
"schoolPlanToConsultStakeholders": "string"
n/a
1. Go to put endpoint confirm new JSON properties
2. go to get endpoint confirm new JSON properties
3. Confirm new columns created in database
n/a

108119 add school consultation persistence

---

.github/workflows/build-and-push-image-test.yml

* Adds a GitHub action to build and push a specific release (eg. tag/sha/branch) to the Test ACR
* Currently set to tag `release-1`

Deploy to Test Azure Container Apps

---

.github/workflows/build-and-push-image-development.yml
.github/workflows/build-and-push-image-test.yml

* The image name (`image_name`) has been set to `aca-app` rather than `academies-academisation-api` within the Azure Container Apps terraform module input variables.

Fix ACR repository name

---

Dfe.Academies.Academisation.WebApi/ActionResults/InternalServerErrorObjectResult.cs
Dfe.Academies.Academisation.WebApi/AutoMapper/AutoMapperProfile.cs
Dfe.Academies.Academisation.WebApi/AutoMapper/AutoMapperSetup.cs
Dfe.Academies.Academisation.WebApi/Controllers/ApplicationController.cs
Dfe.Academies.Academisation.WebApi/Filters/HttpGlobalExceptionFilter.cs
Dfe.Academies.Academisation.WebApi/Middleware/AddCorrelationIdMiddleware.cs
Dfe.Academies.Academisation.WebApi/Middleware/RequestLoggingMiddleware.cs
Dfe.Academies.Academisation.WebApi/Program.cs
Dfe.Academies.Academisation.WebApi/web.config

Tackle 3 OWASP top 10 issues:-
- removed X-Powered-By 
- remove - IIS from response headers
- The value of nosniff will prevent primarily old browsers from MIME-sniffing.
see:-
https://blog.elmah.io/the-asp-net-core-security-headers-guide/

remove response headers if API is ever run in IIS / Azure App service directly

---

terraform/.terraform.lock.hcl
terraform/README.md
terraform/data.tf
terraform/key-vault-tfvars-secrets.tf
terraform/locals.tf
terraform/terraform.tfvars.example
terraform/variables.tf

* Allows providing a list of users that require access to the Key Vault tfvars secrets
* The values should be the User Principle Name found in AD

Add list of Key Vault users

---

.github/workflows/build.yml

Adds the SonarCloud scanner to the build & test github action.
- Scans any PR opened to the main branch and report any outstanding issues.
- Merged Build & Test steps to allow for scanner to cover all
- Added dotnet-coverage around test command to collect results to pipe to SonarCloud

Add sonarcloud scanning to build & test action in github

---

.github/workflows/build.yml

Until we can figure out how to stop dotnet-coverage from suppressing test failures, removing from the sonar scanning

Remove dotnet-coverage from test step to stop silent failures

---

.github/workflows/build.yml

Uses dotCover to collect test coverage results to pipe to SonarCloud.
If unit tests are failing, the build will now fail with this command - see example [here](https://github.com/DFE-Digital/academies-academisation-api/actions/runs/3384728750)

Use dotCover for test coverage in SonarCloud

---

Dfe.Academies.Academisation.Domain.UnitTest/ApplicationAggregate/ApplicationUpdateTests.cs
Dfe.Academies.Academisation.Domain/ApplicationAggregate/Application.cs
Dfe.Academies.Academisation.IDomain/ApplicationAggregate/IApplication.cs
Dfe.Academies.Academisation.IService/Commands/Application/CreateTrustKeyPersonCommand.cs
Dfe.Academies.Academisation.IService/Commands/Application/DeleteSchoolCommand.cs
Dfe.Academies.Academisation.Service/Commands/Application/CreateTrustKeyPersonCommandHandler.cs
Dfe.Academies.Academisation.Service/Commands/Application/DeleteSchoolCommandHandler.cs
Dfe.Academies.Academisation.WebApi/Controllers/ApplicationController.cs

Added an endpoint to delete schools from a FAM application.
May have to be revisited to deleted child objects when they are eventually added
Done on the key people branch I was doing some tidying changes at the same time

116121 Delete school from FAM application

---

.github/workflows/build-and-push-image-development.yml
.github/workflows/build-and-push-image-test.yml

* The set-output command is depreciated. This refactors the workflows to output them into the GITHUB_OUTPUT environment variable instead.
* Warning: The \`set-output\` command is deprecated and will be disabled soon.

Refactor GitHub workflow outputs

---

script/sqlcmd-docker-entrypoint.sh
script/webapi-docker-entrypoint.sh

fix for migration script not working due to quoted_identifier not set

set quoted_identifier on when executing migration script

---

terraform/README.md
terraform/container-apps-hosting.tf
terraform/data.tf
terraform/key-vault-tfvars-secrets.tf
terraform/locals.tf
terraform/variables.tf

What is the change?
Instead of defining all of the terraform for deploying a Key Vault, I have switched to using a terraform module which shifts a lot of the configurable options upstream and reduces the complexity of the terraform code in this repo.
Why do we need the change?
Allows for centralised updates for the Key Vault resource and reduces complexity of the terraform in this repo.
What is the impact?
Applying this terraform change will destroy the existing tfvars Key Vault and recreate it. This has no impact on the running services within Azure and is considered safe/low impact.

Terraform Key Vault tfvars module

---

CypressTests/cypress/e2e/FAM-AddTrustKeyPerson.cy.js
CypressTests/cypress/e2e/Get-UpdateApplication.cy.js
CypressTests/cypress/support/commands.js

Adds a Cypress command to enable test skips when conditions are met.
The command is in support/commands.js and will take any boolean expression as an arg.
Note: to be able to use it and use the Mocha test context, any test will need to use es5 syntax for functions, namely:
it('does a thing', function () { //do something })
rather than
it('does a thing', () => { //do something })
In the skipped tests, I'm currently evaluating against the url containing 'dev' to skip on dev environment, but you may want to change the expression if this won't work.
Also fixes formatting in test classes.

Add test skip capability

---

Dfe.Academies.Academisation.WebApi/Program.cs

Bypassing the API Key check if the environment is Development could be problematic from a security posture point of view.
This PR is a remediation to ensure that all requests must offer a valid API Key

Always use an API Key to authenticate

---

CypressTests/.eslintrc.json
CypressTests/package-lock.json
CypressTests/package.json
README.md

Add eslint to the CypressTests directory. This gives us static code scanning to check for any usual code smells, along with extra rules specifically for Cypress tests.
Also adds a command to the package.json for easy running and updates the README documentation

Add eslint for cypress tests

---

Dfe.Academies.Academisation.WebApi/appsettings.Development.json
Dfe.Academies.Academisation.WebApi/appsettings.json

"Debug" log level is very noisy and shouldn't be used in a development environment by default

Adjust App Settings to reduce LogLevel in Development

---

.github/workflows/build.yml

Java version updated in build action to 17 as 11 is being deprecated by SonarCloud.

Update Java version to 17

---

terraform/README.md
terraform/container-apps-hosting.tf
terraform/locals.tf
terraform/variables.tf

This app has a history of excessive log ingestion which causes a significant spike in cost. 
Setting a sensible alarm threshold of 1GB/day should allow us to have more visibility sooner and allow us to intervene in a runaway scenario

Configure a Log Ingestion rate alarm at >1GB/day

---

terraform/README.md
terraform/container-apps-hosting.tf
terraform/locals.tf
terraform/variables.tf

Granting a User-Assigned Managed Identity the 'AcrPull' role and using that to authenticate with Azure Container Registry follows Microsoft's best practice recommendation instead of using an admin username/password.

Deploy user assigned managed identity

---

.github/workflows/build.yml

Sets paths to restrict when to run build and test.
This is to reduce the amount of times that sonarcloud is ran and to free up github runners

Add exclusion paths for build and test

---

terraform/.terraform.lock.hcl
terraform/README.md
terraform/container-apps-hosting.tf

Remediates ITHC recommendations for Storage Account configurations
1. Ensure 'Cross Tenant Replication' is not enabled
2. Set the default soft delete retention policy to 7 days for blobs and containers
3. Set share retention to default of 7 days
4. Allow operators to opt-out of generating a SAS Connection String for Storage Accounts when not required
5. Set the Azure File Share security profile to 'Maximum Security' as the default which disables SMBv2 and only supports SMBv3

Update Terraform Container App Module to v1.10.1

---

Dfe.Academies.Academisation.WebApi/Middleware/ApiKeyAuthenticationMiddleware.cs

- The healthcheck endpoint is already registered in Program.cs
- We should switch our monitoring from using the swagger index.html file to use the healthcheck endpoint instead. We can only do this if the route is accessible without authentication

Allow unauthenticated access to the health check route

---

Dfe.Academies.Academisation.WebApi/Program.cs

Set a custom User-Agent HTTP Header so that traffic can be segmented when running reports against the downstream APIs

Set HTTP user agent header

---

CypressTests/cypress/e2e/Transfers-MAT.cy.js
CypressTests/cypress/fixtures/payloads/Transfers/AuthorisedUserCanSetAdditionalSchoolData.spec.js

Updates the UKPRN being updated with additional data used by both MAT and SAT Cypress tests. This means both tests can use the same payload properly.
As a result, MAT tests have been updated to check the correct part of the response payload on some tests
Successful run can be seen here: [Run Cypress tests #4](https://github.com/DFE-Digital/academies-academisation-api/actions/runs/10832481262/job/30056942251)

Modify payload and test expectations to match actual behaviour

---

Dfe.Academies.Academisation.Service/Commands/Legacy/Project/EnrichProjectCommand.cs

- remove warning and continue if the trust isn't found, this is a valid scenario for sponsored conversion without a trust

fix for project enrichment - projects without a trust reference

---

Dfe.Academies.Academisation.WebApi/Dfe.Academies.Academisation.WebApi.csproj
Dfe.Academies.Academisation.WebApi/Program.cs

This will ensure that the healthcheck endpoint correctly reports the status of the service if a database connection faults

Add DbContextChecks to Health Checks

---

.github/workflows/build-and-push-image.yml
.github/workflows/docker-build.yml
.github/workflows/docker-test.yml
Dockerfile
script/webapi-docker-entrypoint.sh
terraform/README.md
terraform/container-apps-hosting.tf
terraform/locals.tf
terraform/variables.tf

* Use an `initContainer` to launch an Entity Framework bundle as a preflight container before the main app boots
* This makes the final image smaller and safer because it will no longer container any SQL related data
* Segmenting the workflow into parallel builds ensures the initContainer gets built and imported before the main container gets restarted to avoid any race conditions

Use an initcontainer to run EF Migrations

---

.github/workflows/build.yml

* This workflow will become mandatory so we can't use path filters
* This forms part of the work to make Sonarqube a mandatory quality gate.
Introducing the `sonar.qualitygate.wait=true` parameter ensures that the scanner will wait for the report to be generated and will fail the workflow if the gate is red, rather than completing the workflow regardless of the gate

Removed path filters & wait for quality gate

---

Dockerfile

* Renovate cannot detect the base layer when it has quotes around it

Remove quotation marks from layer name

---

Dfe.Academies.Academisation.Seed/Dfe.Academies.Academisation.Seed.csproj
Dfe.Academies.Academisation.WebApi/Dfe.Academies.Academisation.WebApi.csproj
Dfe.Academies.Academisation.WebApi/Program.cs
Dfe.Academies.Academisation.WebApi/appsettings.Development.json
Dfe.Academies.Academisation.WebApi/appsettings.json

This brings the API in line with other digital services in RSD by using Serilog and App insights as a log sink for traces.
I have also adjusted the default loglevels for different environments in the appsettings.json

Switch to Serilog formatted logs

---

Dfe.Academies.Academisation.Data.UnitTest/ProjectAggregate/ProjectUpdateDataCommandTests.cs
Dfe.Academies.Academisation.Domain.UnitTest/ProjectAggregate/ProjectUpdateTests.cs
Dfe.Academies.Academisation.Domain/ProjectAggregate/Project.cs
Dfe.Academies.Academisation.SubcutaneousTest/ProjectAggregate/LegacyProjectUpdateTests.cs

When an application has been submitted on or after the 20th December 2024, then when updating the project details, data related to Support Grant should be set to null

School Support grant set to null when application submitted after deadline during PUT request
